services:
#  zipkin-server:
#    image: openzipkin/zipkin:3.5.1
#    ports:
#      - "9411:9411"
#    restart: always
#    networks:
#      - erudio-network
#
#  naming-server:
#    image: joaremio/naming-server:latest
#    ports:
#      - "8761:8761"
#    restart: always
#    networks:
#      - erudio-network
#    depends_on:
#      - zipkin-server
#
#  api-gateway:
#    image: joaremio/api-gateway:latest
#    ports:
#      - "8765:8765"
#    restart: always
#    networks:
#      - erudio-network
#    depends_on:
#      - zipkin-server
#      - naming-server
#    environment:
#      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
#
#  book-db:
#    image: postgres:latest
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_USER: docker
#      POSTGRES_PASSWORD: 1234567
#      POSTGRES_DB: book_service
#    networks:
#      - erudio-network
#
#  exchange-db:
#    image: postgres:latest
#    ports:
#      - "5434:5432"
#    environment:
#      POSTGRES_USER: docker
#      POSTGRES_PASSWORD: admin123
#      POSTGRES_DB: exchange_service
#    networks:
#      - erudio-network

  exchange-service:
    image: joaremio/exchange-service:latest
    restart: always
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/exchange_service
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8000:8000"
    networks:
      - erudio-network

  book-service:
    image: joaremio/book-service:latest
    restart: always
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/book_service
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: 1234567
    ports:
      - "8100:8100"
    networks:
      - erudio-network

networks:
  erudio-network:
    name: erudio-network
    driver: bridge